print("account.py created")
print("Master updated account_v1")
print("Master updated account_v2")
print("DEV2 updated account_v1")
print("DEV2 updated ikinci güncelleme yapti, team lead e meydan okuduk")
